### PR TITLE
Golang variant

### PR DESCRIPTION
**Pull request by dertseha**
As requested per #7, this is the pull request for a Go version.
This is mainly a "literal" conversion, including several shortcomings of the CS/Java versions.
See also #10

### CODE REVIEW

**Comment by paulroho** [comment]
@dertseha thank you very much for your PR and sorry for my very late response to it.
I now tried to get it to run on Windows without any prior golang contact and am stuck in executing the specs according to your readme.
Please forgive me my ignorance, but how do I run godog? There is no `godog` folder in `%GOPATH%\bin`. Do I have to unpack the result from the go get command that got me godog? Or do I have to ` go install` anything?

**Comment by dertseha** [comment]
Sorry, now I was taken away by other things.
You'll have to ```go install github.com/DATA-DOG/godog``` and then run it.
(To be honest, I'll have to look up the procedure myself; Which means an update of the readme is definitely necessary ;) Will follow up.

**Comment by dertseha** [comment]
After doing a spring-clean of my GitHub repositories I came across this still open request.
I've finally clarified some steps in the readme that should help newcomers get going easier.

**Comment by paulroho** [comment]
Thank you, @dertseha for your follow-up. As I do not have time to try out myself (being the prototypical clueless regarding the go system), I just merge the PR.

Thanks for the contribution!

**Pull request merged**
